version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Instalando dependencias...
      - mvn install -DskipTests
  build:
    commands:
      - echo Construindo o projeto...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Deploy concluido em `date`
artifacts:
  files:
    - '**/target/*.jar'
  discard-paths: yes
